"""inspections and readings

The first schema. Two tables, and the relationship between them is the design
decision worth reading before changing either — see services/db/models.py:
`inspections.extraction` is the source of truth and `readings` is derived from
it, rebuilt wholesale rather than merged.

Nothing is migrated INTO these tables by this revision. The recordings and
reports already on disk under data/ stay where they are; a backfill that
reads them is its own revision and its own decision, because it has to settle
what to do with the ones whose style set has since changed.

Revision ID: 32907614bd3c
Revises: 
Create Date: 2026-09-23 12:38:15.779846

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32907614bd3c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# JSONB on Postgres, plain JSON everywhere else — the same choice the models
# make. Spelled out here rather than imported from them: a migration that
# follows the models is a migration that changes meaning when the models do,
# which is the one thing a migration must never do.
JSONISH = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('style_no', sa.String(length=32), nullable=False),
    sa.Column('announced_style_no', sa.String(length=32), nullable=False),
    sa.Column('graded_style_no', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('recording_key', sa.String(length=512), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('extraction', JSONISH, nullable=True),
    sa.Column('form', JSONISH, nullable=True),
    sa.Column('outputs', JSONISH, nullable=True),
    sa.Column('sizes', JSONISH, nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('judged', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Integer(), nullable=False),
    sa.Column('out_of_tolerance', sa.Integer(), nullable=False),
    sa.Column('unconfirmed', sa.Integer(), nullable=False),
    sa.Column('accessories', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.Column('measurement_result', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_sha', 'inspections', ['content_sha256'], unique=False)
    op.create_index(
        'ix_inspections_stage_created', 'inspections', ['stage', 'created_at'], unique=False
    )
    op.create_index('ix_inspections_state', 'inspections', ['state'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=32), nullable=False),
    sa.Column('sheet_index', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('pom', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('spec_text', sa.String(length=32), nullable=False),
    sa.Column('spec_sixteenths', sa.Integer(), nullable=True),
    sa.Column('deviation_text', sa.String(length=32), nullable=False),
    sa.Column('deviation_sixteenths', sa.Integer(), nullable=True),
    sa.Column('measured_text', sa.String(length=32), nullable=False),
    sa.Column('measured_sixteenths', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('disputed', sa.Boolean(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'sheet_index', 'size', name='uq_reading_cell')
    )
    op.create_index(op.f('ix_readings_inspection_id'), 'readings', ['inspection_id'], unique=False)
    op.create_index('ix_readings_state', 'readings', ['inspection_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_readings_state', table_name='readings')
    op.drop_index(op.f('ix_readings_inspection_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index('ix_inspections_state', table_name='inspections')
    op.drop_index('ix_inspections_stage_created', table_name='inspections')
    op.drop_index('ix_inspections_sha', table_name='inspections')
    op.drop_table('inspections')
    # ### end Alembic commands ###
