"""audit trail

The `events` table, plus one row per inspection that already exists.

The backfill invents nothing. Every inspection already records who recorded it
and when - `recorded_by_id` and `started_at`, added in 84e7499682f3 - so the
recording events are facts the database is holding anyway, just not in a shape
this screen can read. Without them the trail opens empty on a system that has
been running for weeks, which reads as a broken screen rather than a new one.

Corrections, downloads and releases are not backfilled: nothing wrote those
down, and a log that guesses is worse than one that starts today.

Revision ID: 27ad5b972e48
Revises: 84e7499682f3
Create Date: 2026-09-24 14:58:52.398409

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27ad5b972e48'
down_revision: str | Sequence[str] | None = '84e7499682f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('what', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_at'), 'events', ['at'], unique=False)
    op.create_index(op.f('ix_events_kind'), 'events', ['kind'], unique=False)
    op.create_index(op.f('ix_events_stage'), 'events', ['stage'], unique=False)
    op.create_index('ix_events_stage_at', 'events', ['stage', 'at'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # One "recorded" event per inspection already on file. `uuid_generate`
    # is not assumed to exist, so the ids come from Python.
    events = sa.table(
        "events",
        sa.column("id", sa.Uuid()),
        sa.column("at", sa.DateTime(timezone=True)),
        sa.column("user_id", sa.Uuid()),
        sa.column("actor", sa.String()),
        sa.column("kind", sa.String()),
        sa.column("stage", sa.String()),
        sa.column("what", sa.String()),
        sa.column("subject", sa.String()),
    )
    bind = op.get_bind()
    existing = bind.execute(
        sa.text(
            "SELECT i.id, i.name, i.filename, i.style_no, i.stage, i.started_at,"
            "       i.recorded_by_id, u.name AS actor"
            "  FROM inspections i"
            "  LEFT JOIN users u ON u.id = i.recorded_by_id"
        )
    ).mappings().all()
    if existing:
        op.bulk_insert(
            events,
            [
                {
                    "id": uuid.uuid4(),
                    "at": row["started_at"],
                    "user_id": row["recorded_by_id"],
                    # Empty for anything recorded before sign-in existed. The
                    # screen prints "Unattributed" rather than a name nobody
                    # chose, which is the truth about those rows.
                    "actor": row["actor"] or "",
                    "kind": "record",
                    "stage": row["stage"] or "sizeset",
                    "what": f"Recorded an inspection - {row['filename']}",
                    "subject": (row["name"] or row["style_no"] or row["id"])[:64],
                }
                for row in existing
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index('ix_events_stage_at', table_name='events')
    op.drop_index(op.f('ix_events_stage'), table_name='events')
    op.drop_index(op.f('ix_events_kind'), table_name='events')
    op.drop_index(op.f('ix_events_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
