"""alert dismissal clears

Revision ID: 7e106350b0bd
Revises: 61cc11fb9e4e
Create Date: 2026-09-28 09:36:21.743131

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e106350b0bd'
down_revision: str | Sequence[str] | None = '61cc11fb9e4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'cleared_at')
    # ### end Alembic commands ###
