"""alerts

Revision ID: 61cc11fb9e4e
Revises: 0a72906f34f5
Create Date: 2026-09-28 09:31:03.709712

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61cc11fb9e4e'
down_revision: str | Sequence[str] | None = '0a72906f34f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('rule', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('needs', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_key'), 'alerts', ['key'], unique=False)
    op.create_index('ix_alerts_open', 'alerts', ['stage', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_alerts_raised_at'), 'alerts', ['raised_at'], unique=False)
    op.create_index(op.f('ix_alerts_rule'), 'alerts', ['rule'], unique=False)
    op.create_index(op.f('ix_alerts_stage'), 'alerts', ['stage'], unique=False)
    op.create_index(
        'uq_alert_live',
        'alerts',
        ['key'],
        unique=True,
        # Partial: the resolved history must not block the same condition
        # being raised again next week.
        postgresql_where=sa.text('resolved_at IS NULL'),
        sqlite_where=sa.text('resolved_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_alert_live', table_name='alerts')
    op.drop_index(op.f('ix_alerts_stage'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_raised_at'), table_name='alerts')
    op.drop_index('ix_alerts_open', table_name='alerts')
    op.drop_index(op.f('ix_alerts_key'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
