"""alert settings

Revision ID: 1c73906544cd
Revises: 7e106350b0bd
Create Date: 2026-09-28 10:21:21.334046

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c73906544cd'
down_revision: str | Sequence[str] | None = '7e106350b0bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('threshold_hours', sa.Float(), nullable=True),
    sa.Column('needs', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule', 'stage', name='uq_alert_setting')
    )
    op.create_index(op.f('ix_alert_settings_rule'), 'alert_settings', ['rule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_settings_rule'), table_name='alert_settings')
    op.drop_table('alert_settings')
    # ### end Alembic commands ###
