"""users, memberships and sessions

Who can sign in, what they may do on each stage, and which browsers are
currently signed in.

**The key is a UUID and the credential is an email, and those are two separate
facts.** An earlier draft of this migration keyed on the login name, on the
argument that the audit trail records it. That was backwards: a credential is
exactly the thing that changes, and a key that changes has to be chased through
every row pointing at it. See `services/db/models/user.py`.

Three tables rather than a `role` column on one, because a role is always a
role *in* something: the same person is routinely a reviewer on size set and an
approver on final, and one global role per person is what makes a factory keep
two logins for somebody - which is how an audit trail stops being able to
answer who did what.

Nothing here is seeded. The first administrator is made with
`python src/main.py user add <email> --admin`, deliberately by hand: a default
account with a known password that ships in a migration is a door that stays
open on every deployment that forgets to close it.

Revision ID: b08425f66127
Revises: 32907614bd3c
Create Date: 2026-09-23

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b08425f66127'
down_revision: str | Sequence[str] | None = '32907614bd3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_admin', 'users', ['is_admin'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stage', name='uq_membership_stage')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index('ix_sessions_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_admin', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
