"""alert channels

Who an alert goes to stops being a setting: every one goes to the
administrators, whose addresses the roster already holds. What replaces it is
how it goes — in the app, by email, or both.

Nothing is migrated across. The two columns answer different questions, and
this table has only ever held a handful of rows on one machine.

Revision ID: d06681569137
Revises: 1c73906544cd
Create Date: 2026-09-28 12:07:44.835085

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd06681569137'
down_revision: str | Sequence[str] | None = '1c73906544cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_settings', sa.Column('channels', sa.String(length=64), nullable=False))
    op.drop_column('alert_settings', 'needs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'alert_settings',
        sa.Column('needs', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    )
    op.drop_column('alert_settings', 'channels')
    # ### end Alembic commands ###
