"""reviewer verdict

The call a person makes about the garment, as distinct from `measurement_result`
which is arithmetic. The client's own sheet prints both — MEASUREMENT RESULT
and SIZE SET INSPECTION RESULT — and on a size set the second is "Pass with
comment" more often than not.

`review` is NOT NULL and empty for everything already recorded, which is the
truth: nobody was asked. A report cannot be released until somebody is.

Revision ID: 21654fc035ef
Revises: c898a04ab9ee
Create Date: 2026-09-28 15:01:09.741647

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21654fc035ef'
down_revision: str | Sequence[str] | None = 'c898a04ab9ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL onto a populated table, so the default has to exist for the rows
    # already there — then dropped, because the application always writes these
    # and a default left behind is a second answer to what empty means.
    op.add_column(
        'inspections',
        sa.Column('review', sa.String(length=16), nullable=False, server_default=''),
    )
    op.add_column(
        'inspections',
        sa.Column('review_note', sa.Text(), nullable=False, server_default=''),
    )
    op.alter_column('inspections', 'review', server_default=None)
    op.alter_column('inspections', 'review_note', server_default=None)
    op.add_column(
        'inspections',
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column('inspections', sa.Column('reviewed_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, 'inspections', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'reviewed_by_id')
    op.drop_column('inspections', 'reviewed_at')
    op.drop_column('inspections', 'review_note')
    op.drop_column('inspections', 'review')
    # ### end Alembic commands ###
