"""membership permission overrides

Where one person on one stage differs from their role. Empty for everybody
already on the roster, which is the truth: they were given a preset and
nothing has been changed about it.

Revision ID: 0a72906f34f5
Revises: 27ad5b972e48
Create Date: 2026-09-25 11:31:53.816865

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a72906f34f5'
down_revision: str | Sequence[str] | None = '27ad5b972e48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL onto a populated table, so the default has to exist for the
    # rows that are already there — then dropped, because the application
    # always writes the column and a default left behind is a second source of
    # truth for what an empty override set looks like.
    op.add_column(
        'memberships',
        sa.Column(
            'overrides',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
            server_default='{}',
        ),
    )
    op.alter_column('memberships', 'overrides', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'overrides')
    # ### end Alembic commands ###
