"""inspection title

What a person calls an inspection, as distinct from `name` (the base every
output on disk is filed under, which must not move) and `filename` (whatever
the recorder produced).

Empty for everything already recorded, which is the truth about them: nobody
was asked. The screens fall back to the filename, so they read exactly as they
did before.

Revision ID: d11bf99b76d7
Revises: d06681569137
Create Date: 2026-09-28 12:55:05.114719

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd11bf99b76d7'
down_revision: str | Sequence[str] | None = 'd06681569137'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL onto a populated table, so the default has to exist for the rows
    # already there — then dropped, because the application always writes the
    # column and a default left behind is a second answer to what empty means.
    op.add_column(
        'inspections',
        sa.Column('title', sa.String(length=200), nullable=False, server_default=''),
    )
    op.alter_column('inspections', 'title', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'title')
    # ### end Alembic commands ###
