"""inspection provenance

Revision ID: 84e7499682f3
Revises: 09662e9820c9
Create Date: 2026-09-24 11:22:14.790197

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84e7499682f3'
down_revision: str | Sequence[str] | None = '09662e9820c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('recorded_by_id', sa.Uuid(), nullable=True))
    op.add_column(
        "inspections",
        sa.Column("location", sa.String(length=128), nullable=False, server_default=""),
    )
    op.create_index(
        op.f("ix_inspections_recorded_by_id"), "inspections", ["recorded_by_id"], unique=False
    )
    op.create_foreign_key(
        None, "inspections", "users", ["recorded_by_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column('inspections', 'location', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_index(op.f('ix_inspections_recorded_by_id'), table_name='inspections')
    op.drop_column('inspections', 'location')
    op.drop_column('inspections', 'recorded_by_id')
    # ### end Alembic commands ###
