"""inspection release

An inspection is finished when an approver says it is, not when the pipeline
stops. Null for everything already recorded, which is the truth: nobody has
signed any of them.

Revision ID: c898a04ab9ee
Revises: d11bf99b76d7
Create Date: 2026-09-28 14:25:30.054264

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c898a04ab9ee'
down_revision: str | Sequence[str] | None = 'd11bf99b76d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'inspections',
        sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column('inspections', sa.Column('released_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, 'inspections', 'users', ['released_by_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'released_by_id')
    op.drop_column('inspections', 'released_at')
    # ### end Alembic commands ###
