"""Reads a Triburg graded spec sheet ("style set") out of its PDF.

These are the documents the inspector reads aloud. Each row is one point of
measure: a POM code, a description, a minus and plus tolerance, and the specified
measurement for every size in the range.

The sheets are generated by Triburg's system and carry a real text layer, so the
values are read rather than guessed. A scanned sheet has no text layer and is
rejected with a clear message instead of being silently half-parsed.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from fractions import Fraction
from pathlib import Path

from pypdf import PdfReader

from services.measurements import parse

from .artwork import Artwork, read_artwork

log = logging.getLogger(__name__)

# A row starts with a POM code like "1.23A", or "*" for the free-text notes
# Triburg mixes into the sheet. Some codes carry a " GR" grade-rule marker
# ("7.09B GR"); only that exact suffix is allowed, because a general two-letter
# suffix would swallow the first word of descriptions like "CF BODICE LENGTH".
POM_PATTERN = r"\d\.\d{2}[A-Z]?(?:\s+GR)?|\*"
POM_CODE = re.compile(rf"^({POM_PATTERN})\s+(.*)$")
POM_CODE_ALONE = re.compile(rf"^({POM_PATTERN})$")

# Two layouts come out of Triburg's system. Most exports put a whole row on one
# line; some put every cell on its own line. Both are read rather than one being
# rejected, because the client cannot control which they are given.
COLUMN_HEADER = re.compile(r"^POM\s+Description\s+Tol-\s+Tol\+\s+(.*)$")
CELL_HEADER = ("POM", "Description", "Tol-", "Tol+")

INTEGER = re.compile(r"\d+")

# Every page repeats the sheet's header and footer. Text extraction drops that
# furniture in among the rows — sometimes on the same line as a row's last
# values — and without removing it the row spanning the page break swallows the
# header and reads "Incremental / IN" as measurements.
FURNITURE = (
    r"STATUS:|STYLE:|Company:|Division\s*/\s*Dept:|Season:|Style Desc:|Fit\s*/\s*Other:"
    # "POM Descr :" is metadata; "POM Description Tol- ..." is the column header
    # the parser needs, so the colon has to be part of the match.
    r"|GRADE MEASUREMENTS|Tolerance Model|POM Descr\s*:|Modified By|Modified Date"
    r"|Size Range|Base Size|Grading Method|Date Printed:|Page \d+|\d{4} AEO Management"
)
FOOTER = re.compile(rf"^({FURNITURE}|Block\s*:)", re.IGNORECASE)
FURNITURE_ANYWHERE = re.compile(rf"\b({FURNITURE})", re.IGNORECASE)

# Label on the sheet -> field name. The value sits after the label on the same
# line in the row layout, and on the line below it in the cell layout.
HEADER_LABELS = {
    "style_no": "STYLE:",
    "description": "Style Desc:",
    "company": "Company:",
    "division": "Division / Dept:",
    "season": "Season:",
    "status": "STATUS:",
    "base_size": "Base Size",
    "tolerance_model": "Tolerance Model",
    "pom_descr": "POM Descr",
    "modified_by": "Modified By",
}
TOLERANCE_COLUMNS = 2


class SpecSheetError(RuntimeError):
    """The style set could not be read."""


@dataclass(frozen=True)
class PomRow:
    """One point of measure, with its tolerance band and per-size specification."""

    pom: str
    description: str
    tolerance_minus: Fraction | None
    tolerance_plus: Fraction | None
    specs: dict[str, Fraction | None]

    @property
    def is_note(self) -> bool:
        """Triburg mixes free-text notes into the sheet under a '*' code."""
        return self.pom == "*"

    @property
    def is_measured(self) -> bool:
        """Whether this row carries a real measurement to check against."""
        if self.is_note or not any(v for v in self.specs.values()):
            return False
        return not (self.tolerance_minus == 0 and self.tolerance_plus == 0)

    def spec_for(self, size: str) -> Fraction | None:
        return self.specs.get(size)


@dataclass(frozen=True)
class StyleSet:
    """A whole graded spec sheet."""

    style_no: str
    description: str
    season: str
    division: str
    company: str
    status: str
    base_size: str
    sizes: tuple[str, ...]
    rows: tuple[PomRow, ...]
    source: Path
    tolerance_model: str = ""
    pom_descr: str = ""
    modified_by: str = ""
    artwork: Artwork = field(default_factory=Artwork)

    def measured_rows(self) -> list[PomRow]:
        """Rows carrying a tolerance, so a pass/fail verdict is possible."""
        return [row for row in self.rows if row.is_measured]

    def spoken_rows(self) -> list[PomRow]:
        """Rows the inspector reads aloud, in sheet order.

        Wider than `measured_rows`: position rows and reference rows have no
        tolerance and get no verdict, but they are still read out. Leaving them
        out of the alignment would shift every following row by one.
        """
        return [row for row in self.rows if not row.is_note]

    def find(self, pom: str) -> PomRow | None:
        wanted = pom.strip().casefold()
        return next((row for row in self.rows if row.pom.casefold() == wanted), None)


def _take_values(tokens: list[str], count: int) -> tuple[list[str], list[str]]:
    """Peel `count` measurements off the end of `tokens`, right to left.

    Fractions are written with a space ("30 1/2"), so the count of values is not
    the count of tokens. Reading right to left removes the ambiguity: a fraction
    token claims the integer before it only when there is one.
    """
    values: list[str] = []
    index = len(tokens)
    while len(values) < count and index > 0:
        token = tokens[index - 1]
        if "/" in token and index >= 2 and INTEGER.fullmatch(tokens[index - 2]):
            values.append(f"{tokens[index - 2]} {token}")
            index -= 2
        else:
            values.append(token)
            index -= 1
    values.reverse()
    return values, tokens[:index]


def _header_value(lines: list[str], label: str, first_token: bool = False) -> str:
    """The value printed against `label`, whether beside it or on the line below."""
    for index, line in enumerate(lines):
        position = line.find(label)
        if position < 0:
            continue
        remainder = line[position + len(label) :].strip(" :")
        if not remainder and index + 1 < len(lines):
            remainder = lines[index + 1].strip()
        if first_token:
            return remainder.split()[0] if remainder else ""
        return remainder
    return ""


def _sizes_from_cell_header(lines: list[str]) -> tuple[str, ...]:
    """Size names from a header whose cells are each on their own line."""
    for index in range(len(lines) - len(CELL_HEADER)):
        window = [line.strip() for line in lines[index : index + len(CELL_HEADER)]]
        if window != list(CELL_HEADER):
            continue
        sizes = []
        for line in lines[index + len(CELL_HEADER) :]:
            candidate = line.strip()
            if POM_CODE_ALONE.match(candidate) or parse(candidate) is not None:
                break
            sizes.append(candidate)
        return tuple(sizes)
    return ()


def _parse_cell_layout(lines: list[str], sizes: tuple[str, ...]) -> list[PomRow]:
    """Read rows from a sheet where every cell sits on its own line.

    A row is a POM code, then description lines until the numbers start, then
    exactly one value per tolerance and size column.
    """
    wanted = len(sizes) + TOLERANCE_COLUMNS
    rows: list[PomRow] = []
    index = 0
    while index < len(lines):
        code = POM_CODE_ALONE.match(lines[index].strip())
        if not code:
            index += 1
            continue
        index += 1

        description: list[str] = []
        while index < len(lines) and parse(lines[index].strip()) is None:
            if POM_CODE_ALONE.match(lines[index].strip()):
                break  # a row with no numbers at all; abandon it
            description.append(lines[index].strip())
            index += 1

        values: list[str] = []
        while index < len(lines) and len(values) < wanted:
            value = lines[index].strip()
            if parse(value) is None:
                break
            values.append(value)
            index += 1

        if len(values) == wanted:
            rows.append(
                PomRow(
                    pom=code.group(1),
                    description=" ".join(description).strip(),
                    tolerance_minus=parse(values[0]),
                    tolerance_plus=parse(values[1]),
                    specs={
                        size: parse(value)
                        for size, value in zip(sizes, values[TOLERANCE_COLUMNS:], strict=True)
                    },
                )
            )
    return rows


def _blocks(lines: list[str]) -> list[list[str]]:
    """Group the sheet's lines into one block per POM row.

    A description can wrap onto its own line, with the numbers on the line after,
    so a row is everything from one POM code up to the next.
    """
    blocks: list[list[str]] = []
    for line in lines:
        if POM_CODE.match(line):
            blocks.append([line])
        elif blocks:
            blocks[-1].append(line)
    return blocks


def _parse_row(block: list[str], sizes: tuple[str, ...]) -> PomRow | None:
    """Turn one block into a PomRow, or None if it holds no numbers."""
    joined = " ".join(part.strip() for part in block)
    match = POM_CODE.match(joined)
    if not match:
        return None
    pom, remainder = match.group(1), match.group(2)

    # A row that spans a page break has the next page's header appended to it,
    # sometimes mid-line. The row's own values always precede it, so cut there.
    furniture = FURNITURE_ANYWHERE.search(remainder)
    if furniture:
        remainder = remainder[: furniture.start()]

    wanted = len(sizes) + 2  # the two tolerance columns precede the sizes
    values, description_tokens = _take_values(remainder.split(), wanted)
    if len(values) < wanted:
        return None

    tolerance_minus, tolerance_plus = parse(values[0]), parse(values[1])
    specs = {size: parse(value) for size, value in zip(sizes, values[2:], strict=True)}
    return PomRow(
        pom=pom,
        description=" ".join(description_tokens).strip(),
        tolerance_minus=tolerance_minus,
        tolerance_plus=tolerance_plus,
        specs=specs,
    )


LOOSE_POM = re.compile(r"^(\d\.\d{2}[A-Z]?)\b")


def _unparsed_codes(lines: list[str], rows: list[PomRow]) -> list[str]:
    """POM codes visible in the text that did not survive parsing."""
    seen = {row.pom.split()[0] for row in rows if row.pom != "*"}
    found: list[str] = []
    for line in lines:
        match = LOOSE_POM.match(line.strip())
        if match and match.group(1) not in seen and match.group(1) not in found:
            found.append(match.group(1))
    return found


def _artwork_for(path: Path) -> Artwork:
    """Artwork from this sheet, or from another export of the same style.

    A re-exported sheet like "style_9662_clean.pdf" carries the numbers but not
    the pictures, while the original scan beside it still has them.
    """
    art = read_artwork(path)
    if art:
        return art
    digits = re.search(r"\d+", path.stem)
    if not digits:
        return art
    for sibling in sorted(path.parent.glob(f"*{digits.group()}*.pdf")):
        if sibling == path:
            continue
        found = read_artwork(sibling)
        if found:
            log.info("borrowed artwork for %s from %s", path.name, sibling.name)
            return found
    return art


def read_style_set(path: Path) -> StyleSet:
    """Parse a Triburg style set PDF."""
    if not path.is_file():
        raise SpecSheetError(f"style set not found: {path}")
    try:
        reader = PdfReader(str(path))
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
    except Exception as exc:  # noqa: BLE001 - pypdf raises a wide range of errors
        raise SpecSheetError(f"could not read {path.name}: {exc}") from exc

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        raise SpecSheetError(
            f"{path.name} has no text layer, so it is a scan rather than an export. "
            "Ask Triburg for the generated PDF; the values cannot be read from an image."
        )

    header = {
        name: _header_value(lines, label, first_token=(name == "style_no"))
        for name, label in HEADER_LABELS.items()
    }

    body = [line for line in lines if not FOOTER.match(line)]
    row_layout = next(
        (COLUMN_HEADER.match(line) for line in body if COLUMN_HEADER.match(line)), None
    )

    if row_layout:
        sizes = tuple(row_layout.group(1).split())
        table = [line for line in body if not COLUMN_HEADER.match(line)]
        rows = [row for row in (_parse_row(block, sizes) for block in _blocks(table)) if row]
    else:
        sizes = _sizes_from_cell_header(body)
        if not sizes:
            raise SpecSheetError(
                f"{path.name}: no 'POM Description Tol- Tol+ ...' header found, in either "
                "the one-line-per-row or one-line-per-cell layout"
            )
        rows = _parse_cell_layout(body, sizes)

    if not rows:
        raise SpecSheetError(f"{path.name}: header found but no measurement rows parsed")

    # A row silently dropped shifts every row after it during alignment, so say
    # so loudly. This is how "7.09B GR" went missing and handed belt-length
    # readings to the belt-width row.
    skipped = _unparsed_codes(body, rows)
    if skipped:
        log.warning(
            "%s: %d POM row(s) not parsed and excluded from checking: %s",
            path.name,
            len(skipped),
            ", ".join(skipped),
        )

    style = StyleSet(
        style_no=header.get("style_no", ""),
        description=header.get("description", ""),
        season=header.get("season", ""),
        division=header.get("division", ""),
        company=header.get("company", ""),
        status=header.get("status", ""),
        base_size=header.get("base_size", ""),
        sizes=sizes,
        rows=tuple(rows),
        source=path,
        tolerance_model=header.get("tolerance_model", ""),
        pom_descr=header.get("pom_descr", ""),
        modified_by=header.get("modified_by", ""),
        artwork=_artwork_for(path),
    )
    log.info(
        "read style set %s: %d rows (%d measured) across %s",
        style.style_no or path.stem,
        len(style.rows),
        len(style.measured_rows()),
        ", ".join(sizes),
    )
    return style
