/* Every size-set inspection on the floor.

   Shared by the list (index.html) and the report (report.html) so the two
   cannot disagree about what state something is in — the register saying
   "needs review" while the report opens on a failure is the kind of thing
   nobody notices until a vendor does.

   `state` is the whole story. It decides what the row says, what the report
   renders, and which actions are offered — the same switch the real app makes
   on job.status. */

const INSPECTIONS = [
  {
    id: "7122-4",
    file: "7122(4).mp3",
    style: "7122",
    description: "SMOCKED BUTTON THROUGH",
    season: "Holiday B 2026",
    by: "r.menon",
    when: "21 Sep 09:12",
    len: "14 min 22 s",
    at: "Monday 21 September 2026",
    from: "09:12", to: "09:26",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "10.2 MB", format: "MP3 · 96 kbps CBR · mono 16 kHz",
      device: "Jabra Evolve headset · Android tablet",
      chunks: "862 written to the device while recording",
    },
    transcript: {
      words: "2,436", passes: 2, languages: "English 71% · Hindi 29%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 2,511 timed words",
    },
    lines: [
      ["00:12", "Style seven one two two, smocked button through, size set inspection.", ""],
      ["00:21", "Unit four, twenty first September, inspector R Menon.", ""],
      ["00:34", "साइज़ सेट में चार पीस हैं — S, M, L और XL.", ""],
      ["01:02", "Starting with size S. Front length from HPS to CF, nineteen five by eight, okay.", "1.01A · S"],
      ["01:14", "Shoulder slope from HPS, three by four, okay.", "2.02A · S"],
      ["01:26", "Across shoulder seam to seam relaxed, twelve and a half, minus one by eight.", "1.20A · S"],
      ["01:41", "आगे बढ़ते हैं — across front seam to seam relaxed, eleven, okay.", "1.23A · S"],
      ["01:58", "Across back seam to seam relaxed, eleven and a half, okay.", "1.25A · S"],
      ["02:14", "Chest one inch below armhole relaxed, thirty, minus half.", "1.28A · S"],
      ["02:31", "Bottom opening relaxed last smocking row, thirty one, okay.", "4.22A · S"],
      ["04:06", "Size medium now.", ""],
      ["04:18", "Front length from HPS to CF, twenty one and a half, minus one by eight.", "1.01A · M"],
      ["04:31", "Across shoulder seam to seam relaxed, thirteen —", "1.20A · M"],
      ["04:36", "— sorry, minus one by eight.", "1.20A · M"],
      ["04:52", "Eleven five by eight, minus one by eight.", "1.23A · M"],
      ["05:08", "बैक सीम टू सीम रिलैक्स्ड, बारह, ओके।", "1.25A · M"],
      ["05:24", "Chest one inch below armhole relaxed, thirty two, minus one and a quarter.", "1.28A · M"],
      ["05:31", "That is out — one and a quarter under on the chest.", ""],
      ["08:44", "Size large. Front length twenty two and one eighth, okay.", "1.01A · L"],
      ["09:02", "Across back seam to seam relaxed, twelve three quarter, okay.", "1.25A · L"],
      ["09:40", "Sleeve length from CB longest point, twenty six and a quarter, minus half.", "3.01A · L"],
      ["11:18", "Size XL, front neck drop from HPS to seam, eight five by eight, okay.", "2.03A · XL"],
      ["13:52", "That is the size set. Four accessories checked, all present.", ""],
      ["14:10", "Comments — smocking tension on the medium runs tight at the side seam.", ""],
    ],
    diffs: [
      ["04:52", "1.23A · M", "eleven five by eight minus one by eight", "eleven five eight minus one eight", "The second pass dropped both 'by'. The value agreed, the phrasing did not — 74% confidence."],
      ["04:31", "1.20A · M", "thirteen minus one by eight", "thirteen point one by eight", "Crosstalk over the deviation; the correction at 04:36 settled it — 82%."],
      ["09:02", "1.25A · L", "twelve three quarter", "twelve three quarters", "A plural. Same number — 88%."],
      ["11:18", "2.03A · XL", "eight five by eight", "eight five by eight", "Agreed, but the point of measure was not named on the first pass — 91%."],
    ],
    state: "review",
    rows: 74,
    judged: 71,
    open: 3,
    fail: 2,
    flagged: 4,
    sizes: "S · M · L · XL",
    accessories: 6,
    comments: 4,
    graded: true,
    unconfirmed: [
      ["1.22A", "S", "ACROSS FRONT POSITION FROM HPS", "5"],
      ["1.22A", "M", "ACROSS FRONT POSITION FROM HPS", "5"],
      ["1.24A", "M", "ACROSS BACK POSITION FROM HPS", "5"],
    ],
    outOfTol: [
      ["1.28A", "M", 'CHEST 1" BELOW ARMHOLE — RELAXED', "32", "30 3/4", "−1 1/4"],
      ["3.01A", "L", "SLEEVE LENGTH FROM C.B LONGEST POINT", "26 3/4", "26 1/4", "−1/2"],
    ],
    worth: [
      [18, "M", "ACROSS FRONT SEAM TO SEAM — RELAXED", "11 3/8", "74%",
        "the absolute read aloud matches neither the spec nor this measurement"],
      [12, "M", "ACROSS SHOULDER SEAM TO SEAM — RELAXED", "12 7/8", "82%",
        "crosstalk over the deviation"],
      [31, "L", "ACROSS BACK SEAM TO SEAM — RELAXED", "12 3/4", "88%",
        "mid-sentence correction"],
      [57, "XL", "FRONT NECK DROP FROM HPS TO SEAM", "8 5/8", "91%",
        "name not placed on the first pass"],
    ],
    header: [
      ["Buyer", "American Eagle Outfitters"],
      ["Style", "7122 — smocked button through"],
      ["Season", "Holiday B 2026"],
      ["Factory", "Unit 4, Gurugram"],
      ["Inspector", "R. Menon"],
      ["Date", "21 September 2026"],
      ["Sample stage", "Size set"],
    ],
    unstated: ["PO number", "Colourway", "Order quantity", "Ship date"],
    stats: {
      medianConf: "99%",
      settled: 1,
      // 100% · 95–99 · 90–94 · 85–89 · under 85
      confidence: [52, 9, 5, 3, 2],
      // OK · 1/8 · 1/4 · 3/8 · 1/2 · larger
      deviations: [41, 14, 8, 4, 3, 1],
      bySize: [
        ["S", 18, 18, 0, 1, "100%"],
        ["M", 19, 17, 1, 2, "96%"],
        ["L", 19, 18, 1, 0, "98%"],
        ["XL", 18, 18, 0, 0, "100%"],
      ],
      timing: [
        ["Recording", "14:22"],
        ["First transcription", "3:41"],
        ["Second reading", "3:58"],
        ["Extraction", "0:52"],
        ["Checked against the sheet", "0:04"],
        ["Total", "8:35"],
      ],
    },
  },
  {
    id: "2365-4",
    file: "rec 2365(4).webm",
    style: "2365",
    description: "POPLIN SHIRT DRESS",
    season: "Spring 2027",
    by: "r.menon",
    when: "21 Sep 13:40",
    len: "11 min 58 s",
    at: "Monday 21 September 2026",
    from: "13:40", to: "13:52",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "8.4 MB", format: "WebM · Opus · mono 48 kHz",
      device: "Browser capture · Chrome on Windows",
      chunks: "718 written to the device while recording",
    },
    transcript: {
      words: "—", passes: 1, languages: "not yet known",
      engine: "gpt-transcribe, first pass running",
      index: "not built yet",
    },
    state: "running",
    stage: 1, // 0-based index into the pipeline stages
    message: "Second reading — 8 of 14 minutes",
    elapsed: "4 min 12 s",
    poms: 68,
    sizes: "XS · S · M · L",
    base: "S",
    tolerance: "WW DRS L20",
  },
  {
    id: "7147-1",
    file: "7147(1).mp3",
    style: "7147",
    description: "TIERED MIDI SKIRT",
    season: "Spring 2027",
    by: "s.iqbal",
    when: "21 Sep 08:20",
    len: "9 min 41 s",
    at: "Monday 21 September 2026",
    from: "08:20", to: "08:30",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "6.9 MB", format: "MP3 · 96 kbps CBR · mono 16 kHz",
      device: "Jabra Evolve headset · Android tablet",
      chunks: "581 written to the device while recording",
    },
    transcript: {
      words: "1,604", passes: 2, languages: "English 88% · Hindi 12%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 1,658 timed words",
    },
    lines: [
      ["00:09", "Style seven one four seven, tiered midi skirt, size set.", ""],
      ["00:44", "Size XXS. Waist relaxed, twenty four, okay.", "1.40A · XXS"],
      ["01:12", "Hip eight inches below waist, thirty three and a half, okay.", "1.45A · XXS"],
      ["03:20", "साइज़ XS — waist relaxed, twenty five, okay.", "1.40A · XS"],
      ["05:02", "Size S, skirt length from waist seam, thirty one, minus one by eight.", "4.01A · S"],
      ["07:38", "Size M, bottom sweep, fifty four, okay.", "4.22A · M"],
      ["09:20", "That is the size set. Two accessories checked.", ""],
    ],
    diffs: [
      ["05:02", "4.01A · S", "thirty one minus one by eight", "thirty one minus one eight", "Phrasing only — 86%."],
    ],
    state: "signoff",
    rows: 43,
    judged: 43,
    open: 0,
    fail: 0,
    flagged: 1,
    sizes: "XXS · XS · S · M",
    accessories: 2,
    comments: 1,
    graded: true,
    settled: "Two readings settled by hand by S. Iqbal",
    header: [
      ["Buyer", "American Eagle Outfitters"],
      ["Style", "7147 — tiered midi skirt"],
      ["Season", "Spring 2027"],
      ["Factory", "Unit 4, Gurugram"],
      ["Inspector", "S. Iqbal"],
      ["Date", "21 September 2026"],
      ["Sample stage", "Size set"],
    ],
    unstated: ["PO number", "Ship date"],
    stats: {
      medianConf: "100%",
      settled: 2,
      confidence: [39, 2, 1, 1, 0],
      deviations: [31, 7, 3, 1, 1, 0],
      bySize: [
        ["XXS", 11, 11, 0, 0, "100%"],
        ["XS", 11, 11, 0, 0, "100%"],
        ["S", 11, 11, 0, 0, "98%"],
        ["M", 10, 10, 0, 0, "100%"],
      ],
      timing: [
        ["Recording", "9:41"],
        ["First transcription", "2:30"],
        ["Second reading", "2:41"],
        ["Extraction", "0:38"],
        ["Checked against the sheet", "0:03"],
        ["Total", "5:52"],
      ],
    },
  },
  {
    id: "2365-2",
    file: "2365(2).webm",
    style: "2365",
    description: "POPLIN SHIRT DRESS",
    season: "Spring 2027",
    by: "s.iqbal",
    when: "20 Sep 15:02",
    len: "12 min 30 s",
    at: "Sunday 20 September 2026",
    from: "15:02", to: "15:14",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "9.0 MB", format: "WebM · Opus · mono 48 kHz",
      device: "Browser capture · Chrome on Windows",
      chunks: "750 written to the device while recording",
    },
    transcript: {
      words: "2,118", passes: 2, languages: "English 64% · Hindi 36%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 2,190 timed words",
    },
    lines: [
      ["00:11", "Style two three six five, poplin shirt dress, size set.", ""],
      ["00:52", "Size XS. Front length from HPS, forty one, okay.", "1.01A · XS"],
      ["02:30", "Across shoulder seam to seam relaxed, fourteen, okay.", "1.20A · XS"],
      ["04:15", "साइज़ S — chest one inch below armhole, thirty four, okay.", "1.28A · S"],
      ["07:02", "Size M, sleeve opening relaxed, nine and a half, okay.", "3.19B · M"],
      ["10:24", "Size L, bottom sweep, sixty two, okay.", "4.22A · L"],
      ["12:12", "All sixty eight points measured, nothing out.", ""],
    ],
    diffs: [],
    state: "signoff",
    rows: 68,
    judged: 68,
    open: 0,
    fail: 0,
    flagged: 0,
    sizes: "XS · S · M · L",
    accessories: 5,
    comments: 1,
    graded: true,
    header: [
      ["Buyer", "American Eagle Outfitters"],
      ["Style", "2365 — poplin shirt dress"],
      ["Season", "Spring 2027"],
      ["Factory", "Unit 4, Gurugram"],
      ["Inspector", "S. Iqbal"],
      ["Date", "20 September 2026"],
      ["Sample stage", "Size set"],
    ],
    unstated: ["Colourway", "Order quantity"],
    stats: {
      medianConf: "100%",
      settled: 0,
      confidence: [64, 3, 1, 0, 0],
      deviations: [52, 9, 5, 1, 1, 0],
      bySize: [
        ["XS", 17, 17, 0, 0, "100%"],
        ["S", 17, 17, 0, 0, "100%"],
        ["M", 17, 17, 0, 0, "100%"],
        ["L", 17, 17, 0, 0, "99%"],
      ],
      timing: [
        ["Recording", "12:30"],
        ["First transcription", "3:12"],
        ["Second reading", "3:20"],
        ["Extraction", "0:44"],
        ["Checked against the sheet", "0:04"],
        ["Total", "7:20"],
      ],
    },
  },
  {
    id: "2463-1",
    file: "2463(1)(3).m4a",
    style: "—",
    announced: "2463",
    description: "RIBBED HENLEY, LONG SLEEVE",
    season: "Fall A 2026",
    by: "s.iqbal",
    when: "20 Sep 16:04",
    len: "9 min 06 s",
    at: "Sunday 20 September 2026",
    from: "16:04", to: "16:13",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "6.5 MB", format: "M4A · AAC 128 kbps · mono 44.1 kHz",
      device: "Phone recorder · uploaded afterwards",
      chunks: "not captured in the browser",
    },
    transcript: {
      words: "1,512", passes: 2, languages: "English 58% · Hindi 42%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 1,571 timed words",
    },
    lines: [
      ["00:08", "Style two four six three, ribbed henley, long sleeve.", ""],
      ["00:46", "Size S. Front length from HPS, twenty six, okay.", ""],
      ["02:20", "साइज़ M — chest one inch below armhole, thirty six.", ""],
      ["05:14", "Size L, sleeve length from CB, thirty four and a half.", ""],
      ["08:50", "That is all three sizes.", ""],
    ],
    diffs: [],
    state: "ungraded",
    rows: 71,
    judged: 0,
    sizes: "S · M · L",
    accessories: 3,
    comments: 2,
    graded: false,
  },
  {
    id: "9662-1",
    file: "Recording_9662(1).mp3",
    style: "9662",
    description: "CROPPED CARDIGAN, RIB TRIM",
    season: "Fall A 2026",
    by: "r.menon",
    when: "20 Sep 11:19",
    len: "41 s",
    at: "Sunday 20 September 2026",
    from: "11:19", to: "11:20",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "0.5 MB", format: "MP3 · 96 kbps CBR · mono 16 kHz",
      device: "Jabra Evolve headset · Android tablet",
      chunks: "41 written to the device while recording",
    },
    transcript: {
      words: "96", passes: 2, languages: "English 100%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 101 timed words",
    },
    lines: [
      ["00:03", "Testing, testing.", ""],
      ["00:19", "है ना? हाँ ठीक है।", ""],
      ["00:33", "Okay we will start after lunch.", ""],
    ],
    diffs: [],
    state: "failed",
    error:
      "TranscriptError: the transcript came back with no point of measure\nin it. Expected a style number and a size to be announced within\nthe first two minutes; found neither.",
    reason: "The recording holds 41 seconds of audio and no measurements.",
  },
  {
    id: "9601-2",
    file: "9601(2).mp3",
    style: "9601",
    description: "QUILTED SHACKET",
    season: "Holiday B 2026",
    by: "r.menon",
    when: "19 Sep 14:55",
    len: "13 min 07 s",
    at: "Saturday 19 September 2026",
    from: "14:55", to: "15:08",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "9.4 MB", format: "MP3 · 96 kbps CBR · mono 16 kHz",
      device: "Jabra Evolve headset · Android tablet",
      chunks: "787 written to the device while recording",
    },
    transcript: {
      words: "2,204", passes: 2, languages: "English 69% · Hindi 31%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 2,281 timed words",
    },
    lines: [
      ["00:14", "Style nine six zero one, quilted shacket, size set.", ""],
      ["01:05", "Size XS. Chest one inch below armhole relaxed, thirty seven, okay.", "1.28A · XS"],
      ["03:40", "Size S, sleeve opening relaxed, ten, okay.", "3.19B · S"],
      ["06:18", "साइज़ M — across back seam to seam, sixteen and a quarter, okay.", "1.25A · M"],
      ["08:52", "Size L, chest one inch below armhole relaxed, thirty nine three quarter, minus one and a quarter.", "1.28A · L"],
      ["08:59", "That one is out — one and a quarter under.", ""],
      ["12:40", "Size XL, bottom opening relaxed, forty four, okay.", "4.22A · XL"],
    ],
    diffs: [
      ["03:40", "3.19B · M", "ten and a quarter", "ten a quarter", "A dropped 'and' — 86%."],
      ["12:40", "4.22A · XL", "forty four", "forty four okay", "The verdict ran into the value — 89%."],
    ],
    state: "review",
    rows: 61,
    judged: 61,
    open: 0,
    fail: 1,
    flagged: 2,
    sizes: "XS · S · M · L · XL",
    accessories: 4,
    comments: 3,
    graded: true,
    outOfTol: [
      ["1.28A", "L", 'CHEST 1" BELOW ARMHOLE — RELAXED', "41", "39 3/4", "−1 1/4"],
    ],
    worth: [
      [22, "M", "SLEEVE OPENING — RELAXED", "10 1/4", "86%", "crosstalk over the deviation"],
      [44, "XL", "BOTTOM OPENING RELAXED", "44", "89%", "mid-sentence correction"],
    ],
    header: [
      ["Buyer", "American Eagle Outfitters"],
      ["Style", "9601 — quilted shacket"],
      ["Season", "Holiday B 2026"],
      ["Factory", "Unit 4, Gurugram"],
      ["Inspector", "R. Menon"],
      ["Date", "19 September 2026"],
      ["Sample stage", "Size set"],
    ],
    unstated: ["PO number", "Colourway", "Ship date"],
    stats: {
      medianConf: "99%",
      settled: 0,
      confidence: [51, 6, 2, 1, 1],
      deviations: [44, 10, 4, 2, 1, 0],
      bySize: [
        ["XS", 12, 12, 0, 0, "100%"],
        ["S", 12, 12, 0, 0, "99%"],
        ["M", 12, 12, 0, 0, "97%"],
        ["L", 13, 13, 1, 0, "100%"],
        ["XL", 12, 12, 0, 0, "100%"],
      ],
      timing: [
        ["Recording", "13:07"],
        ["First transcription", "3:22"],
        ["Second reading", "3:30"],
        ["Extraction", "0:47"],
        ["Checked against the sheet", "0:04"],
        ["Total", "7:43"],
      ],
    },
  },
  {
    id: "9685-1",
    file: "9685(1).m4a",
    style: "9685",
    description: "WIDE LEG TROUSER, PLEAT FRONT",
    season: "Spring 2027",
    by: "s.iqbal",
    when: "18 Sep 10:31",
    len: "10 min 12 s",
    at: "Friday 18 September 2026",
    from: "10:31", to: "10:41",
    location: "Unit 4, Gurugram · size-set bench, floor 2",
    recording: {
      size: "7.3 MB", format: "M4A · AAC 128 kbps · mono 44.1 kHz",
      device: "Phone recorder · uploaded afterwards",
      chunks: "not captured in the browser",
    },
    transcript: {
      words: "1,847", passes: 2, languages: "English 81% · Hindi 19%",
      engine: "gpt-transcribe, twice",
      index: "Deepgram nova-3 · 1,903 timed words",
    },
    lines: [
      ["00:10", "Style nine six eight five, wide leg trouser, pleat front, size set.", ""],
      ["00:58", "Size XXS. Waist relaxed, twenty three and a half, okay.", "1.40A · XXS"],
      ["02:44", "Size XS, inseam, twenty nine, okay.", "4.11A · XS"],
      ["05:10", "साइज़ S — front rise, eleven and a quarter, okay.", "4.05A · S"],
      ["07:32", "Size M, leg opening, twenty two, okay.", "4.20A · M"],
      ["09:48", "Size L, outseam, forty and a half, okay.", "4.12A · L"],
      ["10:02", "Fifty seven points, nothing out of tolerance.", ""],
    ],
    diffs: [],
    state: "released",
    rows: 57,
    judged: 57,
    open: 0,
    fail: 0,
    flagged: 0,
    sizes: "XXS · XS · S · M · L",
    accessories: 3,
    comments: 0,
    graded: true,
    signedBy: "P. Grewal",
    signedOn: "18 Sep 16:20",
    header: [
      ["Buyer", "American Eagle Outfitters"],
      ["Style", "9685 — wide leg trouser"],
      ["Season", "Spring 2027"],
      ["Factory", "Unit 4, Gurugram"],
      ["Inspector", "S. Iqbal"],
      ["Date", "18 September 2026"],
      ["Sample stage", "Size set"],
    ],
    unstated: ["Colourway"],
    stats: {
      medianConf: "100%",
      settled: 0,
      confidence: [54, 2, 1, 0, 0],
      deviations: [47, 7, 2, 1, 0, 0],
      bySize: [
        ["XXS", 11, 11, 0, 0, "100%"],
        ["XS", 12, 12, 0, 0, "100%"],
        ["S", 11, 11, 0, 0, "100%"],
        ["M", 12, 12, 0, 0, "100%"],
        ["L", 11, 11, 0, 0, "99%"],
      ],
      timing: [
        ["Recording", "10:12"],
        ["First transcription", "2:41"],
        ["Second reading", "2:48"],
        ["Extraction", "0:40"],
        ["Checked against the sheet", "0:03"],
        ["Total", "6:12"],
      ],
    },
  },
];

/* What each state is called, and how loudly. */
const STATES = {
  running: ["Processing", "pill warning"],
  review: ["Needs review", "pill lavender"],
  signoff: ["Waiting for sign-off", "pill success"],
  released: ["Signed off", "pill"],
  ungraded: ["Not graded", "pill"],
  failed: ["Failed", "pill error"],
};

/* What the confidence and deviation histograms are buckets of. Named here
   because two screens read them and a bucket list that lives in one of them
   is a bucket list that will disagree with the other. */
const CONF_BUCKETS = ["100%", "95–99%", "90–94%", "85–89%", "under 85%"];
const DEV_BUCKETS = ["OK", "1/8", "1/4", "3/8", "1/2", "larger"];

function inspection(id) {
  return INSPECTIONS.find((job) => job.id === id) || null;
}

function reportUrl(job) {
  return "report.html?id=" + encodeURIComponent(job.id);
}
